<a href="https://colab.research.google.com/github/vionajlk462-dot/my-python-projectvio/blob/main/numpy_%26_pandas_vio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np

#menggunakan kurung siku tunggal untuk memvisualisasikan secara vektor
vektor1= np.array([2,4,6,8])
print(vektor1)
print(vektor1.shape)

#menggunakan kurung siku ganda untuk membuat matriks
matriks1= np.array([[2,3,4,],[8,12,14]])
print(matriks1)
print(matriks1.shape)

[2 4 6 8]
(4,)
[[ 2  3  4]
 [ 8 12 14]]
(2, 3)

In [ ]:
import numpy as np
#mengubah ukuran matriks menggunakan fungsi reshape
matriks2= np.array([[2,3,4],[8,12,14]])
print('2,3',matriks2.shape)
matriksnew=matriks2.reshape(3,2)
print(matriksnew)

#membuat matriks 3 dimensi
#matriksnew2=matriks2.reshape(2,4,3)
#tidak bisa membuat 3 dimensi karena size yang ada terlalu kecil sehingga saya harus reshape ulang/menambah data di array

2,3 (2, 3)
[[ 2  3]
 [ 4  8]
 [12 14]]

In [ ]:
import numpy as np
#membuat data dengan menggunakan fungsi np.arange
range1=np.arange(0, 8)
print(range1)

#membuat matriks mengggunakan fungsi np.arange
range2=np.arange(0,8).reshape(4,2)
print(range2)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

In [ ]:
import numpy as np
#membuat matriks kelipatan menggunakan np.arange
kelipatan1=np.arange(8,80,8) # Membuat angka kelipatan 8, mulai dari 8 sampai sebelum 80
print(kelipatan1)

#membuat matriks kelipatan  menggunakan np.arange dan memakai fungsi reshape
kelipatan2=np.arange(2,60,4).reshape(5,3)
print(kelipatan2)

[ 8 16 24 32 40 48 56 64 72]
[[ 2  6 10]
 [14 18 22]
 [26 30 34]
 [38 42 46]
 [50 54 58]]

In [ ]:
import numpy as np
#Membuat slicing dan indexing
nampay1=([1,2,3,4,5])
print(nampay1[3]) #indexing(mengambil 1 elemen dalam array)
print(nampay1[2:]) #mulai dari posisi 2 hingga posisi terakhir
print(nampay1[-2:]) #mengambil 2 elemen terakhir dari kanan ke kiri
print(nampay1[2:4]) #slicing(mengambil n-rentang elemen dalam array)

4
[3, 4, 5]
[4, 5]
[3, 4]

In [ ]:
import numpy as np
urutan, jarak = np.linspace(0, 1, 5, retstep=True)
print("Urutan:", urutan)
print("Jarak antara elemen:", jarak)

Urutan: [0.   0.25 0.5  0.75 1.  ]
Jarak antara elemen: 0.25

# **PANDAS**

In [ ]:

#menjalankan pandas dan numpy
import pandas as pd
import numpy as np
#menampilkan array 1 dimensi
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
data = pd.Series(['a','b','c'])
np1 = np.array(['x','y','z'])
data_np = pd.Series(np1)
print(data)
print(data_np)
#mengatur indeks pada numpy array data-np di atas
data_np = pd.Series(np1, index=[2,3,4])
print(data_np)

0    a
1    b
2    c
dtype: object
0    x
1    y
2    z
dtype: object
2    x
3    y
4    z
dtype: object

In [ ]:
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
#operasi jumlah
dsa = ds1 + ds2
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2
print(dsa)
print(dsb)
print(dsc)
print(dsd)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
#konversi pandas module Series ke python list
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series dan type")
print(ds)
print(type(ds))
print("Konver Pandas Series ke Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series dan type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Konver Pandas Series ke Python list
[2, 4, 6, 8, 10]
<class 'list'>

In [ ]:
#konversi a NumPy array to a Pandas series
import numpy as np
import pandas as pd

np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_np = pd.Series(np_array)
print("konversi Pandas series:")
print(new_np)

NumPy array:
[ 0 20 30 40 50]
konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
#generate angka random
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series)
print(num_state)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
RandomState(MT19937)

In [ ]:
#P7.1 load data dari folder yang sama dengan coding
df = pd.read_csv('penjualan.csv')
print(df)
# Boleh menampilkan sesuai selera
#df.info()
#df.tail()
df.shape
df.nama.head()
df[df['nama'] == 'Chandra']

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85
8   Indara  320  374  300  270
9     Joni  200  220  175  155

      nama  jan  feb  mar  apr
2  Chandra  300  315  285  190

In [ ]:
df = pd.read_csv('fiskal97.csv')
#print(df)
#df.head()
#df.info()
#df.describe()
df[['Tahun','PAD']]
df.sort_values(by='PAD',ascending=False)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
1052,Kota Tarakan,2021,310.26,237.35,166.72,413.94,269.95,308.14,292.04,686.78,...,176.48,120.64,235.66,267.83,156.10,5.21,5.49,0.36,66.56,4.13
967,Kota Cilegon,2024,222.11,193.53,146.37,465.72,253.62,236.20,322.04,616.90,...,128.73,51.84,171.32,275.23,162.52,9.82,3.72,0.31,62.36,7.57
570,Kota Malang,2023,230.13,146.90,116.35,477.08,277.64,271.48,224.39,611.50,...,275.60,59.95,205.74,65.17,293.26,5.58,9.10,0.40,69.96,2.87
251,Kota Pekanbaru,2023,277.09,215.37,92.45,317.57,288.44,213.47,236.88,604.75,...,219.38,55.64,156.72,94.58,188.51,6.00,7.54,0.31,69.39,6.39
976,Kota Tangerang,2022,292.00,162.60,139.18,480.05,188.25,207.17,255.61,596.15,...,253.12,229.32,181.06,197.20,222.28,5.54,9.89,0.39,68.98,2.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,Kota Tual,2016,13.46,5.94,9.03,24.84,16.41,18.73,15.04,27.71,...,279.32,283.85,165.95,213.73,114.48,16.62,9.63,0.32,63.89,5.76
914,Kota Tual,2015,12.96,8.93,10.32,24.69,15.56,16.35,19.12,27.30,...,135.24,83.42,71.53,59.82,263.13,17.91,6.13,0.48,71.70,4.69
786,Kota Kotamobagu,2019,13.13,10.64,10.93,32.37,25.78,24.42,17.71,27.25,...,162.51,159.06,78.41,175.48,264.96,17.68,9.38,0.46,63.20,5.70
782,Kota Kotamobagu,2015,14.14,11.61,6.73,27.46,14.62,14.05,21.82,25.74,...,106.52,99.39,297.28,107.03,294.63,16.81,9.89,0.30,77.48,5.89
783,Kota Kotamobagu,2016,11.55,10.02,10.74,22.33,17.62,16.66,20.79,24.06,...,254.33,251.29,116.26,280.56,52.67,15.22,7.76,0.43,83.56,6.35